// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExportProject(arg1:main.Project):Promise<main.Project>;

export function GenerateAudio(arg1:main.Project):Promise<main.Project>;

export function GenerateImage(arg1:main.Project,arg2:number):Promise<main.Project>;

export function GenerateProject(arg1:main.Project):Promise<main.Project>;

export function GenerateVideo(arg1:main.Project,arg2:number):Promise<main.Project>;

export function GetMediaData(arg1:string):Promise<string>;

export function GetProject():Promise<main.Project>;

export function GetSettings():Promise<main.Settings>;

export function NewProject():Promise<main.Project>;

export function PlanStory(arg1:main.PlanRequest):Promise<main.Project>;

export function SaveProject(arg1:main.Project):Promise<void>;

export function SaveSettings(arg1:main.Settings):Promise<void>;
