// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportProject(arg1) {
  return window['go']['main']['App']['ExportProject'](arg1);
}

export function GenerateAudio(arg1) {
  return window['go']['main']['App']['GenerateAudio'](arg1);
}

export function GenerateImage(arg1, arg2) {
  return window['go']['main']['App']['GenerateImage'](arg1, arg2);
}

export function GenerateProject(arg1) {
  return window['go']['main']['App']['GenerateProject'](arg1);
}

export function GenerateVideo(arg1, arg2) {
  return window['go']['main']['App']['GenerateVideo'](arg1, arg2);
}

export function GetMediaData(arg1) {
  return window['go']['main']['App']['GetMediaData'](arg1);
}

export function GetProject() {
  return window['go']['main']['App']['GetProject']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function NewProject() {
  return window['go']['main']['App']['NewProject']();
}

export function PlanStory(arg1) {
  return window['go']['main']['App']['PlanStory'](arg1);
}

export function SaveProject(arg1) {
  return window['go']['main']['App']['SaveProject'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}
